name: Build

on:
  issue_comment:
    types: [created]

jobs:
  apk:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    if: (github.actor == 'robertsLando' || github.actor == 'n1ru4l') && github.event.issue.url == 'https://api.github.com/repos/robertsLando/pkg-binaries/issues/5'
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1

      - name: "Build ${{ github.event.comment.body }}"
        timeout-minutes: 360
        id: build
        run: |
          sudo apt-get install -y rename
          chmod +x build.sh
          ./build.sh ${{ github.event.comment.body }}
          FETCHED=$(ls | grep fetched)
          NODE_MAJOR=$(echo ${{ github.event.comment.body }} | awk '{print $2}')
          echo "::set-output name=FETCHED::$FETCHED"
          echo "::set-output name=NODE_MAJOR::$NODE_MAJOR"
      - name: Upload {{ steps.build.outputs.FETCHED }} to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ steps.build.outputs.FETCHED }}
          asset_name: ${{ steps.build.outputs.FETCHED }}
          tag: ${{ steps.build.outputs.NODE_MAJOR }}
          overwrite: true
